// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using microsvc.services.DbRepos.Order;

namespace microsvc.services.Migrations.orderdb
{
    [DbContext(typeof(orderContext))]
    [Migration("20220312001918_seed-data")]
    partial class seeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23");

            modelBuilder.Entity("microsvc.services.DbRepos.Order.OrderEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("int");

                    b.Property<double?>("TotalSpent")
                        .HasColumnType("REAL");

                    b.Property<long?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrderEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
